version: '3'

services:
  # Database setup
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mysql-db-name
      MYSQL_USER: mysql-db-user
      MYSQL_PASSWORD: mysql-db-password
    networks:
      - wpsite
  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root 
    networks:
      - wpsite
  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '3000:80'
    restart: always
    volumes: ['./wp-content:/var/www/html/wp-content']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: mysql-db-name
      WORDPRESS_DB_USER: mysql-db-user
      WORDPRESS_DB_PASSWORD: mysql-db-password
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data:
